on:
  workflow_dispatch:

name: update-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@master
        with:
          extra-packages: |
            rcmdcheck
            pkgdown
            dieghernan/pkgdev
            V8
          needs: website

      - name: Update docs
        run: |

          pkgdev::update_docs()

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Update docs with pkgdev' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - uses: r-lib/actions/check-r-package@master

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

