name: Clear all Github actions caches manually
on:
  workflow_dispatch:
  schedule:
    - cron: '45 10 10 * *'

jobs:
  cache-clear:
    runs-on: ubuntu-latest

    steps:
      - uses: easimon/wipe-cache@main

